Quacker/Controllers/HomeController.cs
using Quacker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quacker.Controllers
{
    public class HomeController : Controller
    {
        private QuackerDB db = new QuackerDB();

        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Landing", "Home");
            }
            var quackList = (from a in db.QuackTable where a.QuackId != null orderby a.Date descending select a);
            var NewQuacks = quackList.Take(3).ToList();
            Random random = new Random();
            

            var RandomQuacks = quackList.Skip(random.Next(0, db.QuackTable.Count() - 5)).Take(5).ToList();
            var quacks = new UserViewQuacks();
            quacks.NewQuacks = NewQuacks;
            quacks.RandomQuacks = RandomQuacks;
            return View(quacks);
        }
        public ActionResult Landing()
        {
            var quacks = db.QuackTable.ToList();
            Random random = new Random();
            Quack quack = quacks.ElementAt(random.Next(0, quacks.Count()));
            return View(quack);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Quacker/Controllers/QuacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quacker.Models;

namespace Quacker.Controllers
{
    public class QuacksController : Controller
    {
        private QuackerDB db = new QuackerDB();

        // GET: Quacks
        public ActionResult Index()
        {
            var quackTable = db.QuackTable.Include(q => q.User);
            return View(quackTable.ToList());
        }

        public ActionResult ViewQuacks()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            var id = Session["UserID"] as int?;
            var quackTable = db.QuackTable.Where(quack => quack.UserId == id);
            return View(quackTable.ToList());
        }
        // GET: Quacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quack quack = db.QuackTable.Include(q => q.User).SingleOrDefault(q => q.QuackId == id);
            if (quack == null)
            {
                return HttpNotFound();
            }
            return View(quack);
        }

        // GET: Quacks/Create
        public ActionResult Create()
        {
            if (Session["UserID"] == null) {
                return RedirectToAction("Login", "Users");
            }
            return View();
        }

        // POST: Quacks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuackId,Title,Text")] Quack quack)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            quack.UserId = Session["UserID"] as int? ?? default(int);
            quack.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.QuackTable.Add(quack);
                db.SaveChanges();
                return RedirectToAction("ViewQuacks");
            }
            return View(quack);
        }

        // GET: Quacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quack quack = db.QuackTable.Find(id);
            if (quack == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserTable, "UserId", "FirstName", quack.UserId);
            return View(quack);
        }

        // POST: Quacks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuackId,Title,Text")] Quack quack)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (ModelState.IsValid)
            {
                var modifiedQuack = db.QuackTable.Find(quack.QuackId);
                modifiedQuack.Title = quack.Title;
                modifiedQuack.Text = quack.Text;
                db.Entry(modifiedQuack).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserTable, "UserId", "FirstName", quack.UserId);
            return View(quack);
        }

        // GET: Quacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quack quack = db.QuackTable.Find(id);
            if (quack == null)
            {
                return HttpNotFound();
            }
            return View(quack);
        }

        // POST: Quacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            Quack quack = db.QuackTable.Find(id);
            db.QuackTable.Remove(quack);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quacker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Quacker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Quacker/Views/Home/Index.cshtml
@model Quacker.Models.UserViewQuacks

@{
    ViewBag.Title = "Index";
}

<h2>Home </h2>

<div>
    <div class="col-md-4">
        <table class="table">
            <tr>
                <th>
                    Random Quacks you might like
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model.RandomQuacks)
            {
            <tr>
                <td>
                    @Html.ActionLink(item.Title, "Details", "Quacks", new { id = item.QuackId }, null)
                </td>
            </tr>
             }
        </table>
    </div>
    <div>
        @foreach (var item in Model.NewQuacks)
        {

            <div class="card  mb-3">
                <div class="card-header"> <h4 class="card-text">@item.Title</h4> </div>
                <div class="card-body">
                    <p class="card-text">@item.Text</p>
                    <p class="card-text">@item.Date</p>
                </div>
            </div>
        }


    </div>
</div>

Quacker/Views/Home/Landing.cshtml
@model Quacker.Models.Quack
@{
    ViewBag.Title = "Landing";
}

<div class="jumbotron">
    <h1>Welcome To Quacker</h1>
    <p class="lead">Find out what people are saying and the latest news.</p>
    <p>@Html.ActionLink("Register Now", "Register", "Users")</p>
</div>


    <div >
        <h2>Quack of the day</h2>
        <h3>@Html.DisplayFor(m => m.Title) </h3>
        <p>@Html.DisplayFor(m => m.Text) </p>
    </div>